# Generated by Django 4.2.16 on 2024-10-16 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gear_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sport_type', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
                ('duration', models.DurationField()),
                ('start_date', models.DateTimeField()),
                ('gears', models.ManyToManyField(blank=True, to='gear_app.gear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
