# Generated by Django 4.2.16 on 2024-10-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='elevation_gain',
            field=models.FloatField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
