# Generated by Django 4.2.16 on 2024-10-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0002_activity_elevation_gain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='strava_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
