# Generated by Django 4.2.16 on 2024-10-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_app', '0006_equipment_user'),
        ('activities_app', '0003_alter_activity_strava_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='gears',
            field=models.ManyToManyField(blank=True, to='gear_app.equipment'),
        ),
    ]
