# Generated by Django 4.2.16 on 2024-11-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_app', '0007_shoesize_alter_equipment_brand_alter_equipment_model_and_more'),
        ('activities_app', '0004_alter_activity_gears'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='gears',
            field=models.ManyToManyField(blank=True, related_name='activities', to='gear_app.equipment'),
        ),
    ]
