# Generated by Django 4.2.16 on 2025-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0005_alter_activity_gears'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
