# Generated by Django 4.2.16 on 2025-05-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0006_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='average_heartrate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='average_speed',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
