# Generated by Django 4.2.16 on 2025-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0007_activity_average_heartrate_activity_average_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='average_heartrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='average_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
