# Generated by Django 4.2.16 on 2025-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0008_alter_activity_average_heartrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='sport_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
