# Generated by Django 4.2.16 on 2025-06-05 11:58

from django.db import migrations, models

def copy_duration_to_moving_time(apps, schema_editor):
    Activity = apps.get_model('activities_app', 'Activity')
    for activity in Activity.objects.all():
        activity.moving_time = activity.duration
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('activities_app', '0009_alter_activity_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='moving_time',
            field=models.DurationField(null=True, blank=True),
        ),
        migrations.RunPython(copy_duration_to_moving_time),
    ]