# Generated by Django 4.2.9 on 2024-01-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintextt",
            name="text_field",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
