# Generated by Django 4.2.16 on 2024-10-16 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_distance', models.FloatField(default=0.0)),
                ('total_uses', models.IntegerField(default=0)),
                ('retailer', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_log', models.TextField(blank=True, null=True)),
                ('estimated_lifespan_km', models.FloatField(blank=True, null=True)),
                ('gear_type', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gears', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
