# Generated by Django 4.2.16 on 2024-10-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_app', '0002_sport_gear_model_equipmenttype_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
