# Generated by Django 4.2.16 on 2024-10-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_app', '0003_equipment_custom_fields_equipment_maintenance_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='custom_field_structure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
