# Generated by Django 4.2.16 on 2024-10-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear_app', '0004_equipmenttype_custom_field_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear_app.sport'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear_app.equipmenttype'),
        ),
    ]
