# Generated by Django 4.2.16 on 2024-11-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_app', '0006_equipment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_size', models.CharField(blank=True, max_length=10, null=True)),
                ('uk_size', models.CharField(blank=True, max_length=10, null=True)),
                ('eu_size', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
