# Generated by Django 4.2.16 on 2025-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_app', '0007_shoesize_alter_equipment_brand_alter_equipment_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='default_use',
            field=models.TextField(blank=True, null=True),
        ),
    ]
