# Generated by Django 4.2.16 on 2025-05-13 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gear_app', '0008_equipment_default_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='default_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_use_sports', to='gear_app.sport'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_equipments', to=settings.AUTH_USER_MODEL),
        ),
    ]
