# Generated by Django 4.2.16 on 2025-06-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_app', '0009_alter_equipment_default_use_alter_equipment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'In active use'), ('secondary', 'Secondary use'), ('disposed', 'Disposed')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
