# Generated by Django 4.2.16 on 2025-06-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_app', '0010_equipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='default_use',
        ),
        migrations.AddField(
            model_name='equipment',
            name='default_uses',
            field=models.ManyToManyField(blank=True, related_name='default_use_equipments', to='gear_app.sport'),
        ),
    ]
