# Generated by Django 4.2.16 on 2025-07-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gear_app", "0011_remove_equipment_default_use_equipment_default_uses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("unselected", "Select status"),
                    ("active", "In active use"),
                    ("secondary", "Secondary use"),
                    ("disposed", "Disposed"),
                ],
                default="unselected",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
