# Generated by Django 4.2.16 on 2024-10-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_synced',
            new_name='strava_token_expires_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strava_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strava_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
