# Generated by Django 4.2.16 on 2024-10-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_last_synced_userprofile_strava_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
