# Generated by Django 4.2.16 on 2025-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_userprofile_last_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_synced',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
