# Generated by Django 3.2.2 on 2023-01-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_maintextt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textin',
            fields=[
                ('maintextt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.maintextt')),
            ],
            bases=('blog.maintextt',),
        ),
    ]
