branch-defaults:
  default:
    environment: mysite-dev
environment-defaults:
  mysite-dev:
    branch: null
    repository: null
global:
  application_name: mysite
  default_ec2_keyname: django_app
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
